---
title: "Slido"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

## Preview

```{r, echo = FALSE, hide = TRUE}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
yaml <- yaml::read_yaml(file.path(root_dir, "_config_automation.yml"))

## For Slido
joined_participants <- readr::read_tsv(file.path("metricminer_data", "slido", "JoinedParticipants.tsv"))
leaderboard <- readr::read_tsv(file.path("metricminer_data", "slido", "Leaderboard.tsv"))
polls <- readr::read_tsv(file.path("metricminer_data", "slido", "Polls-overall.tsv"))
questions <- readr::read_tsv(file.path("metricminer_data", "slido", "Questions.tsv"))
```

## Setting up Slido

```{r child='resources/child/slido.Rmd'}
```

## Customizing the Slido Data

```{r, include=FALSE}
customization_data_source <- "your Slido"
customization_refresh_script <- "`refresh-scripts/refresh-slido.R`"
```

```{r child='resources/child/customization-data.Rmd'}
```
