---
title: "YouTube"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

## Preview

```{r, echo = FALSE, hide = TRUE, message = FALSE, warning = FALSE}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
yaml <- yaml::read_yaml(file.path(root_dir, "_config_automation.yml"))

## For Youtube
youtube <- readr::read_tsv(file.path("metricminer_data", "youtube", "youtube.tsv"))

## For youtube
```

## Data information

- `viewCount` how many times has the video been viewed?
- `likeCount` how many times has the video been liked?
- `dislikeCount` - how many times has the video been disliked?
- `favoriteCount` - how many times has the video been favorited?
- `commentCount` - how many comments on the video?

```{r}
knitr::kable(youtube)
```

## Setting up YouTube

```{r child='resources/child/youtube.Rmd'}
```

## Customizing the YouTube Data

```{r, include=FALSE}
customization_data_source <- "your YouTube"
customization_refresh_script <- "`refresh-scripts/refresh-youtube.R`"
```

```{r child='resources/child/customization-data.Rmd'}
```
